### ISSUE TITLE
Error executing process EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE with exit status 125

### ISSUE THREAD

**Issue by xeniaroda29** [EBI-Metagenomics/mettannotator#38] opened 2024-07-15 12:18 UTC
### Description of the bug

I encountered an error while running the EBIMETAGENOMICS_METTANNOTATOR pipeline. The process EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE (BA_CL3) terminated with an error exit status (125).

### Command used and terminal output

```console
Command used:
nextflow run ebi-metagenomics/mettannotator -r main -profile docker --input input_file/assemblies_sheet.csv  --outdir output/ --dbs databases/


Error Message:
ERROR ~ Error executing process > 'EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE (BA_CL3)'

Caused by:
  Process `EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE (BA_CL3)` terminated with an error exit status (125)

Command executed:

  echo "Pre-processed UniFIRE input file"
  prepare_unifire_input.py -i unifire/BA_CL3.faa -t 1390 -o unifire
  
  # This is the provided docker running script
  /opt/scripts/bin/unifire-workflow.sh
  
  make_combined_unifire_output.py -i unifire -o unifire/BA_CL3.combined_predictions.out
  
  cat <<-END_VERSIONS > versions.yml
  "EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE":
      UniFIRE: 2023.4
  END_VERSIONS

Command exit status:
  125

Command output:
  (empty)

Command error:
  unknown flag: --bind
  See 'docker run --help'.

Work dir:
  /media/sequentia/isilon/consultoria/E24007_v1-Gema_Llorens/pacbio_data/BMK240212-BW908-ZX01-0101/BMK_DATA_20240611141606_1/Data/project/genome_annotation/mettannotator/work/38/998c1c3a56d2386210626c53f42f5d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

### Relevant files

[nextflow.log](https://github.com/user-attachments/files/16234430/nextflow.log)

**Comment by mberacochea** [comment] 2024-07-15 16:40
Hi @xeniaroda29 thank you for reporting the issue. This is a bug in the unifire process, it should be fixed in bugfix/38-unifire-mount-docker.

Could you try to run it from that branch?
```bash
nextflow run ebi-metagenomics/mettannotator \
-r bugfix/38-unifire-mount-docker \
-profile docker \
--input input_file/assemblies_sheet.csv \
--outdir output/ \
--dbs databases/
```

**Comment by xeniaroda29** [comment] 2024-07-16 07:58
> Hi @xeniaroda29 thank you for reporting the issue. This is a bug in the unifire process, it should be fixed in [bugfix/38-unifire-mount-docker](https://github.com/EBI-Metagenomics/mettannotator/pull/39).
> 
> Could you try to run it from that branch?
> 
> ```shell
> nextflow run ebi-metagenomics/mettannotator \
> -r bugfix/38-unifire-mount-docker \
> -profile docker \
> --input input_file/assemblies_sheet.csv \
> --outdir output/ \
> --dbs databases/

> ```

Hi @mberacochea,

First of all, thanks for your rapid response! I tried to run the command, but now I have another error regarding a file from the AMRfinderPlus database:

Error:

FINISHED --2024-07-16 07:24:54--
  Total wall clock time: 14m 43s
  Downloaded: 37 files, 119M in 13m 36s (149 KB/s)
  Running: amrfinder_index 2024-01-31.1
  Indexing
  
  *** ERROR ***
  '/usr/local/bin/hmmpress'  -f '2024-01-31.1/AMR.LIB' > /dev/null 2> /tmp/amrfinder_index.j9YOuL/hmmpress.err
  status = 256
  bad file format in HMM file 2024-01-31.1/AMR.LIB
  
  HOSTNAME: 92b7f6e7d61b
  SHELL: ?
  PWD: /media/sequentia/isilon/consultoria/E24007_v1-Gema_Llorens/pacbio_data/BMK240212-BW908-ZX01-0101/BMK_DATA_20240611141606_1/Data/project/genome_annotation/mettannotator/work/13/39931fc2703cea1d18ab5a60e312cf
  PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/xroda/.nextflow/assets/ebi-metagenomics/mettannotator/bin
  Progam name:  amrfinder_index
  Command line: amrfinder_index 2024-01-31.1

Work dir:
  /media/sequentia/isilon/consultoria/E24007_v1-Gema_Llorens/pacbio_data/BMK240212-BW908-ZX01-0101/BMK_DATA_20240611141606_1/Data/project/genome_annotation/mettannotator/work/13/39931fc2703cea1d18ab5a60e312cf




I checked the database link and it is correct, but there might be an issue with the AMR.LIB file. I have attached the .nextflow.log: 
[nextflow.log](https://github.com/user-attachments/files/16244962/nextflow.log)


Thanks in advance.

**Comment by mberacochea** [comment] 2024-07-16 12:44
Hi @xeniaroda29,

OK, I'm glad the Unifire issue was sorted. The error with the AMRFinder DB is something I haven't seen before. I'm running it locally to try to reproduce the error.

In the meantime, I recommend deleting the databases/amrfinder folder and re-running the pipeline. This will force the process to run again (maybe it was a transient problem).

Cheers

**Comment by MWorksGH** [comment] 2024-07-16 15:57
Thank you!
I ran into the same problem, tried the fix, and a new error message is displayed:
-[ebi-metagenomics/mettannotator] Pipeline completed with errors-
[dc/815afa] NOTE: Missing output file(s) `unifire/predictions_arba.out` expected by process `EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:UNIFIRE (myGenome)` -- Execution is retried (1)                                                ERROR ~ Error executing process > 'EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:INTERPROSCAN (myGenome)'

Caused by:
  Process `EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:INTERPROSCAN (myGenome)` terminated with an error exit status (125)


Command executed:

  interproscan.sh     -cpu 16     -dp     --goterms     -pa     -f TSV     --input myGenome.faa     -o myGenome.IPS.tsv

  cat <<-END_VERSIONS > versions.yml
  "EBIMETAGENOMICS_METTANNOTATOR:METTANNOTATOR:INTERPROSCAN":
      InterProScan: $(interproscan.sh --version | grep -o "InterProScan version [0-9.-]*" | sed "s/InterProScan version //")
      InterProScan database: 5.62-94.0

  END_VERSIONS

Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Error response from daemon: create interproscan/data: "interproscan/data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
  See 'docker run --help'.

Work dir:
  /home/data/myName/mettannotator/work/63/f3fc186144b41691cea590f6c7c8d7

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details


Any help will be appreciated.

**Comment by mberacochea** [comment] 2024-07-20 10:06
Hi @MWorksGH 

I've fixed the issues with InterproScan and Unifire, and also a memory problem with emapper.

Could you please run the pipeline from the following branch "bugfix/ips-unipro-docker-mounts-fix"?

```bash
$ nextflow run ebi-metagenomics/mettannotator -r bugfix/ips-unipro-docker-mounts-fix -profile docker --input input_file/assemblies_sheet.csv --outdir output/ --dbs databases/
```
There is also a local profile that limits the max memory to 8 cores and the mem to 12GB, this more suitable for desktop workstations (just add `-profile docker,local`).

**Comment by MWorksGH** [comment] 2024-07-20 23:48
> Hi @MWorksGH
> 
> I've fixed the issues with InterproScan and Unifire, and also a memory problem with emapper.
> 
> Could you please run the pipeline from the following branch "bugfix/ips-unipro-docker-mounts-fix"?
> 
> ```shell
> $ nextflow run ebi-metagenomics/mettannotator -r bugfix/ips-unipro-docker-mounts-fix -profile docker --input input_file/assemblies_sheet.csv --outdir output/ --dbs databases/
> ```
> 
> There is also a local profile that limits the max memory to 8 cores and the mem to 12GB, this more suitable for desktop workstations (just add `-profile docker,local`).

Hi @mberacochea, I have just finished my test and it worked flawlessly! 
Thank you very much, have a great weekend!

**Comment by MWorksGH** [comment] 2024-07-20 23:48
> Hi @MWorksGH
> 
> I've fixed the issues with InterproScan and Unifire, and also a memory problem with emapper.
> 
> Could you please run the pipeline from the following branch "bugfix/ips-unipro-docker-mounts-fix"?
> 
> ```shell
> $ nextflow run ebi-metagenomics/mettannotator -r bugfix/ips-unipro-docker-mounts-fix -profile docker --input input_file/assemblies_sheet.csv --outdir output/ --dbs databases/
> ```
> 
> There is also a local profile that limits the max memory to 8 cores and the mem to 12GB, this more suitable for desktop workstations (just add `-profile docker,local`).

Hi @mberacochea, I have just finished my test and it worked flawlessly! 
Thank you very much, have a great weakend!

**Comment by mberacochea** [comment] 2024-07-21 10:06
Brilliant @MWorksGH. Thanks for reporting the issue, I'll make a new release of the pipeline this week.

**Closed by mberacochea** 2024-07-21 10:06 UTC
Labels: bug
